//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyBanHang
{
    using System;
    using System.Collections.Generic;
    
    public partial class HoaDon
    {
        public int MaHD { get; set; }
        public string TenKhachHang { get; set; }
        public Nullable<int> TongTien { get; set; }
        public Nullable<System.DateTime> NgayLap { get; set; }
        public string NVLapHD { get; set; }
        public string TrangThai { get; set; }
    
        public virtual ChiTietHoaDon ChiTietHoaDon { get; set; }
        public virtual NhanVien NhanVien { get; set; }
    }
}
